
# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Default terminal is 256 colors
set -g default-terminal "screen-256color"

set -g default-shell /bin/bash
set -g mouse on

setw -g pane-border-status top
setw -g pane-base-index 1     # make pane numbering consistent with windows

set -g base-index 1           # start windows numbering at 1
set -g renumber-windows on    # renumber windows when a window is closed

# No delay for escape key press
set -sg escape-time 0

set-environment -g 'IGNOREEOF' 1

bind b send-keys -R \; clear-history

bind-key  s set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"
bind-key -n M-. select-window -n
bind-key -n M-, select-window -p

# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"

