
# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Default terminal is 256 colors
set -g default-terminal "tmux-256color"

set -g default-shell /bin/bash
set -g mouse on

setw -g pane-border-status top
setw -g pane-base-index 1     # make pane numbering consistent with windows

set -g base-index 1           # start windows numbering at 1
set -g renumber-windows on    # renumber windows when a window is closed

# No delay for escape key press
set -sg escape-time 0

# git status
set -g status-right '#(~/bin/gitmux "#{pane_current_path}")'

set-environment -g 'IGNOREEOF' 1

bind BSpace send-keys -R \; clear-history
bind s set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

bind -r C-Right select-window -n
bind -r C-Left select-window -p

